#pragma once


namespace RE
{
	enum class ExtraDataType : UInt8
	{
		kNone,						// 0x00
		kHavok,						// 0x01
		kCell3D,					// 0x02
		kCellWaterType,				// 0x03
		kRegionList,				// 0x04
		kSeenData,					// 0x05
		kEditorID,					// 0x06
		kCellMusicType,				// 0x07
		kCellSkyRegion,				// 0x08
		kProcessMiddleLow,			// 0x09
		kDetachTime,				// 0x0A
		kPersistentCell,			// 0x0B
		kUnk0C,						// 0x0C
		kAction,					// 0x0D
		kStartingPosition,			// 0x0E
		kUnk0F,						// 0x0F
		kAnimGraphManager,			// 0x10
		kUnk11,						// 0x11
		kUsedMarkers,				// 0x12
		kDistantData,				// 0x13
		kRagDollData,				// 0x14
		kContainerChanges,			// 0x15
		kWorn,						// 0x16
		kWornLeft,					// 0x17
		kPackageStartLocation,		// 0x18
		kPackage,					// 0x19
		kTresPassPackage,			// 0x1A
		kRunOncePacks,				// 0x1B
		kReferenceHandle,			// 0x1C
		kFollower,					// 0x1D
		kLevCreaModifier,			// 0x1E
		kGhost,						// 0x1F
		kOriginalReference,			// 0x20
		kOwnership,					// 0x21
		kGlobal,					// 0x22
		kRank,						// 0x23
		kCount,						// 0x24
		kHealth,					// 0x25
		kUnk26,						// 0x26
		kTimeLeft,					// 0x27
		kCharge,					// 0x28
		kLight,						// 0x29
		kLock,						// 0x2A
		kTeleport,					// 0x2B
		kMapMarker,					// 0x2C
		kLeveledCreature,			// 0x2D
		kLeveledItem,				// 0x2E
		kScale,						// 0x2F
		kMissingLinkedRefIDs,		// 0x30
		kMagicCaster,				// 0x31
		kNonActorMagicTarget,		// 0x32
		kUnk33,						// 0x33
		kPlayerCrimeList,			// 0x34
		kUnk35,						// 0x35
		kEnableStateParent,			// 0x36
		kEnableStateChildren,		// 0x37
		kItemDropper,				// 0x38
		kDroppedItemList,			// 0x39
		kRandomTeleportMarker,		// 0x3A
		kUnk3B,						// 0x3B
		kSavedHavokData,			// 0x3C
		kCannotWear,				// 0x3D
		kPoison,					// 0x3E
		kMagicLight,				// 0x3F
		kLastFinishedSequence,		// 0x40
		kSavedAnimation,			// 0x41
		kNorthRotation,				// 0x42
		kSpawnContainer,			// 0x43
		kFriendHits,				// 0x44
		kHeadingTarget,				// 0x45
		kUnk46,						// 0x46
		kRefractionProperty,		// 0x47
		kStartingWorldOrCell,		// 0x48
		kHotkey,					// 0x49
		kUnk4A,						// 0x4A
		kEditiorRefMoveData,		// 0x4B
		kInfoGeneralTopic,			// 0x4C
		kHasNoRumors,				// 0x4D
		kSound,						// 0x4E
		kTerminalState,				// 0x4F
		kLinkedRef,					// 0x50
		kLinkedRefChildren,			// 0x51
		kActivateRef,				// 0x52
		kActivateRefChildren,		// 0x53
		kCanTalkToPlayer,			// 0x54
		kObjectHealth,				// 0x55
		kCellImageSpace,			// 0x56
		kNavMeshPortal,				// 0x57
		kModelSwap,					// 0x58
		kRadius,					// 0x59
		kUnk5A,						// 0x5A
		kFactionChanges,			// 0x5B
		kDismemberedLimbs,			// 0x5C
		kActorCause,				// 0x5D
		kMultiBound,				// 0x5E
		kMultiBoundData,			// 0x5F - kMultiBoundData, removed in 1.7.7.0
		kMultiBoundRef,				// 0x60
		kReflectedRefs,				// 0x61
		kReflectorRefs,				// 0x62
		kEmittanceSource,			// 0x63
		kRadioData,					// 0x64 - kRadioData, removed in 1.7.7.0
		kCombatStyle,				// 0x65
		kUnk66,						// 0x66
		kPrimitive,					// 0x67
		kOpenCloseActivateRef,		// 0x68
		kAnimNoteReceiver,			// 0x69
		kAmmo,						// 0x6A
		kPatrolRefData,				// 0x6B
		kPackageData,				// 0x6C
		kOcclusionShape,			// 0x6D
		kCollisionData,				// 0x6E
		kSayTopicInfoOnceADay,		// 0x6F
		kEncounterZone,				// 0x70
		kSayTopicInfo,				// 0x71
		kOcclusionPlaneRefData,		// 0x72
		kPortalRefData,				// 0x73
		kPortal,					// 0x74
		kRoom,						// 0x75
		kHealthPerc,				// 0x76
		kRoomRefData,				// 0x77
		kGuardedRefData,			// 0x78
		kCreatureAwakeSound,		// 0x79
		kUnk7A,						// 0x7A
		kHorse,						// 0x7B
		kIgnoredBySandbox,			// 0x7C
		kCellAcousticSpace,			// 0x7D
		kReservedMarkers,			// 0x7E
		kWeaponIdleSound,			// 0x7F
		kWaterLightRefs,			// 0x80
		kLitWaterRefs,				// 0x81
		kWeaponAttackSound,			// 0x82
		kActivateLoopSound,			// 0x83
		kPatrolRefInUseData,		// 0x84
		kAshPileRef,				// 0x85
		kCreatureMovementSound,		// 0x86
		kFollowerSwimBreadcrumbs,	// 0x87
		kAliasInstanceArray,		// 0x88
		kLocation,					// 0x89
		kUnk8A,						// 0x8A
		kLocationRefType,			// 0x8B
		kPromotedRef,				// 0x8C
		kUnk8D,						// 0x8D
		kOutfitItem,				// 0x8E
		kUnk8F,						// 0x8F
		kLeveledItemBase,			// 0x90
		kLightData,					// 0x91
		kSceneData,					// 0x92
		kBadPosition,				// 0x93
		kHeadTrackingWeight,		// 0x94
		kFromAlias,					// 0x95
		kShouldWear,				// 0x96
		kFavorCost,					// 0x97
		kAttachedArrows3D,			// 0x98
		kTextDisplayData,			// 0x99
		kAlphaCutoff,				// 0x9A
		kEnchantment,				// 0x9B
		kSoul,						// 0x9C
		kForcedTarget,				// 0x9D
		kUnk9E,						// 0x9E
		kUniqueID,					// 0x9F
		kFlags,						// 0xA0
		kRefrPath,					// 0xA1
		kDecalGroup,				// 0xA2
		kLockList,					// 0xA3
		kForcedLandingMarker,		// 0xA4
		kLargeRefOwnerCells,		// 0xA5
		kCellWaterEnvMap,			// 0xA6
		kCellGrassData,				// 0xA7
		kTeleportName,				// 0xA8
		kInteraction,				// 0xA9
		kWaterData,					// 0xAA
		kWaterCurrentZoneData,		// 0xAB
		kAttachRef,					// 0xAC
		kAttachRefChildren,			// 0xAD
		kGroupConstraint,			// 0xAE
		kScriptedAnimDependence, 	// 0xAF
		kCachedScale,				// 0xB0
		kRaceData,					// 0xB1
		kGIDBuffer,					// 0xB2
		kMissingRefIDs				// 0xB3
	};
}
