name: Apply Formatting

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/formatting.yml'
      - 'include/**/*.h'
      - 'src/**/*.h'
      - 'src/**/*.cpp'
  pull_request:
    branches: [ master ]
  pull_request_target:
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format-12 -style=file -i

    - uses: stefanzweifel/git-auto-commit-action@v4.9.0
      with:
        commit_message: apply formatting
