name: Apply Formatting

on: [ push, pull_request, pull_request_target ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format-12 -style=file -i

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: apply formatting
